#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sklearn.linear_model import LinearRegression
from TaxiFareModel.data import get_data, clean_data
from sklearn.model_selection import train_test_split
from TaxiFareModel.trainer import Trainer
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

#Create list of estimators to evaluate
models = {"Linear Regression": LinearRegression(), "Rand Forest": RandomForestRegressor(), "XGB": XGBRegressor()}

# get data
df = get_data()

#clean data
df = clean_data(df)

# set X and y
y = df["fare_amount"]
X = df.drop("fare_amount", axis=1)

# hold out
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.15)

#iterate over different estimators
for key, value in models.items():

    #instanciate trainer
    trainer = Trainer(X_train, y_train, model=value)

    # train the pipeline
    trainer.run()

    # evaluate the pipeline + upload on MLFlow
    trainer.evaluate(X_val, y_val)

    #save model
    trainer.save_model()
